### PR TITLE
Fix clipboardy/webpack issue - breaking release 1.3.17

### PR DESCRIPTION
**Pull request by Tatsinnit**
Hi Everyone,

Thank you all for your continued collaboration and support. ❤️

### Solution:

* Temporary but moving forward - Downgraded this package use to `2.3.0` 
    *  **Please try this VSIX**: [vscode-kubernetes-tools-1.3.17-12hari-tats.vsix.zip](https://github.com/user-attachments/files/17319962/vscode-kubernetes-tools-1.3.17-12hari-tats.vsix.zip)
* Long term: Its only used in one file, we can reaccess the use and remove it if not needed, with something simpler or in-house. Under #1357 

Thank you so much for calls and chats and our effort to systematically go through the list of PR's @hsubramanianaks ❤️ <3 and all especially ❤️ @anime-shed , @kejatura-dev, @ReinierCC, Also, an FYI, so suppress work will stay as it is.:  @qpetraroia, @corneliusroemer, @okgolove, @tejhan, @gambtho, @squillace, 

~It seems like we might have more to investigate regarding `suppressOutput`. From what I've observed, there's a potential issue or dependency mentioned in #1354 that's affecting the extension as a whole, especially on Windows. I haven’t noticed this on Mac yet, but please refer to #1354, particularly **this comment that hinted** at a deeper issue beyond the logger file ([#907](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/907#issuecomment-819224756))~. To actively track this, could we replicate the issue and scope out its impact, @qpetraroia and @hsubramanianaks? Let's also monitor elating issues mentioned in #1208 for further insights.

~For now, I’ve reverted a specific commit (7d514ce) to keep things moving forward without breaking functionality. I believe this might help in making progress without unintended disruptions.~

(if anyone wants to but given the suppress is untouched I hope its fixed now) ~If anyone could share a screencast of the behavior, that would be extremely helpful. And of course, community contributions are more than welcome for anyone keen to help resolve this!~

~The plan is to replicate the original issue which was fixed under #1208 and handle it case by case, or try to simplify the fix if possible. Any ideas or suggestions are greatly appreciated.~

Thanks again, and I look forward to working through this together!

fyi: @okgolove , @corneliusroemer,  @kejatura-dev, @qpetraroia , @hsubramanianaks , @ReinierCC & @tejhan cc: @squillace + @gambtho

### CODE REVIEW

**Comment by Tatsinnit** [comment]
VSIX to test , 
[vscode-kubernetes-tools-1.3.18-testrevert.vsix.zip](https://github.com/user-attachments/files/17301722/vscode-kubernetes-tools-1.3.18-testrevert.vsix.zip)

* Please download and instead of unzipping just rename without `*.zip` 
* Then, use the vscode `install from vsix` feature to install this six and it will fix the extension issues.

Thanks,

**Comment by hsubramanianaks** [comment]
> tried this but I am not getting any error but also `kubeconfig` not being read
> 
> image
> 
> No issues with `v1.3.16` though.
> 
> image

is this windows or different OS ? Please clarify.

**Review by hsubramanianaks — APPROVED** [review]
Thanks @Tatsinnit for quick fixing this. I have tested in windows and Linux works in both platforms with your revert fix. Without the revert fix, it works in Linux (ubuntu) but not in windows (I was able to replicate the issue).

**Comment by anime-shed** [comment]
@

> > tried this but I am not getting any error but also `kubeconfig` not being read
> > image
> > No issues with `v1.3.16` though.
> > image
> 
> is this windows or different OS ? Please clarify.

image

**Comment by Tatsinnit** [comment]
Thanks you so much all: <3 plus one if this works please.

**Please try this VSIX**: [vscode-kubernetes-tools-1.3.17-12hari-tats.vsix.zip](https://github.com/user-attachments/files/17319962/vscode-kubernetes-tools-1.3.17-12hari-tats.vsix.zip)

**Review by qpetraroia — APPROVED** [review]

**Comment by qpetraroia** [comment]
Works for me! Thank you for this fix!

**Review by hsubramanianaks — APPROVED** [review]
looks good to me, we tested in windows, ubuntu and mac all works fine.

**Comment by kejatura-dev** [comment]
This works for me too [vscode-kubernetes-tools-1.3.17-12hari-tats.vsix.zip](https://github.com/user-attachments/files/17319962/vscode-kubernetes-tools-1.3.17-12hari-tats.vsix.zip). Thanks!

**Pull request merged**
