### PR TITLE
Added snippet for ReplicaSet

### PR DESCRIPTION
**Pull request by dbreyfogle**
Fixes https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/669

### CODE REVIEW

**Review by Tatsinnit — APPROVED** [review]
Looks good to me, thank you for contribution. Will wait for anyone else who would like to review and then merge it in coming day. Thanks heaps.

**Review by Moazzem-Hossain-pixel — APPROVED** [review]
Thanks for your support.

**Review by Moazzem-Hossain-pixel — APPROVED** [review]
Thanks

**Review by Moazzem-Hossain-pixel — APPROVED** [review]
Thanks

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Thanks

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Tnanks

**Pull request merged**
