### PR TITLE
Publish 1.3.4

### PR DESCRIPTION
**Pull request by itowlson**

### CODE REVIEW

**Comment by tmds** [comment]
The extension still isn't released. Is it still due to the issue with the release token?

**Comment by squillace** [comment]
yes, @tmds, my apologies. It's on me to get this properly wired up. Setting out to do this now. Let's see if I can circumvent the world here. :-)

**Comment by squillace** [comment]
Failed twice. Will keep at it. I appreciate the patience.

**Comment by squillace** [comment]
@tmds, I believe we were able to solve the problem and published the release.

**Comment by tmds** [comment]
@squillace, I've just installed `1.3.4`. Thank you!

**Comment by squillace** [comment]
it's a miracle, frankly

**Pull request merged**
